In [1]:
import model

m = model.ContextUnet(in_channels=1)

In [2]:
import torch
x = torch.randn(1,1,48,56,48)

In [2]:
%%bash
python -u main.py --mode train --dataset dataset_rh --labels pipelines \
   --batch_size 1 --data_dir data \
   --n_epoch 10 --lrate 1e-4 --drop_prob 0.2 --n_T 1

Dataset dataset_rh: 
 19200 images.
Epoch 0


bash: line 3: 92391 Killed: 9               python -u main.py --mode train --dataset dataset_rh --labels pipelines --batch_size 1 --data_dir data --n_epoch 10 --lrate 1e-4 --drop_prob 0.2 --n_T 1


CalledProcessError: Command 'b'python -u main.py --mode train --dataset dataset_rh --labels pipelines \\\n   --batch_size 1 --data_dir data \\\n   --n_epoch 10 --lrate 1e-4 --drop_prob 0.2 --n_T 1\n'' returned non-zero exit status 137.

In [26]:
import torch
x= torch.randn(24,1,48,56,48)
torch.randint(1, 400+1, (x.shape[0],)).shape

torch.Size([24])

In [48]:
c = torch.tensor([[0,0,0,1,0], [0,1,0,0,0], [0,0,0,1,0], [0,0,0,1,0]])

context_mask = torch.bernoulli(torch.zeros_like(torch.argmax(c, dim=1))+0.9)
print(context_mask)

tensor([1., 1., 1., 1.])


In [49]:
context_mask = context_mask[:, None]
print(context_mask)
context_mask = context_mask.repeat(1,5)
context_mask = (-1*(1-context_mask)) # need to flip 0 <-> 1
c = c * context_mask
print(c)

tensor([[1.],
        [1.],
        [1.],
        [1.]])
tensor([[-0., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0.]])


In [50]:
torch.arange(0,24)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [53]:
c_i = torch.arange(0,24) # context for us just cycles throught the labels
c_i = c_i.repeat(int(24/c_i.shape[0]))
c_i = c_i.repeat(2)

In [56]:
import torch.nn as nn
nn.functional.one_hot(c_i, num_classes=24).type(torch.float)

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [ ]:
c_i = c_i.repeat(2)